algoritmo "Exercicio_26"
var
   n1, n2: Inteiro
inicio
      Escreva("Digite um número: ")
      Leia(n1)
      Escreva("Digite mais um número: ")
      Leia(n2)
      Se (n1>n2) entao
         Escreva("O primeiro valor é maior")
      Senao
           Se(n2>n1) entao
             Escreva("O segundo valor é maior")
           Senao
                Escreva("Não existe valor maior, os dois são iguais")
           FimSe
      FimSe
      
fimalgoritmo
